/**
 * Mock data for the BoxProfilePage.
 * This mirrors the shape of data the real API will eventually return,
 * so wiring it up later is a straightforward swap in useBoxProfile.js.
 */

import { calculateRoi } from './formatters';

export const MOCK_BOX = {
  id: 'topps-chrome-2023-hobby',
  name: '2023 Topps Chrome Baseball',
  manufacturer: 'Topps',
  year: 2023,
  format: 'Hobby',
  imageUrl: 'https://cdn.shopify.com/s/files/1/0662/9749/5709/files/b4919d4bfc6a19370b7af14a9e3e62d161b13060_blob.png?v=1772612167',
  config: {
    packsPerBox: 18,
    cardsPerPack: 4,
    totalCards: 72,
  },
  pricing: {
    // Current sealed box market price from eBay sold listings
    marketPrice: 189.99,
    // Original manufacturer suggested retail price
    msrp: 149.99,
    // Expected value: probability-weighted sum of all pull values
    expectedValue: 162.5,
    // ROI calculated via the shared formula in utils/formatters.js
    roi: calculateRoi(162.5, 189.99),
  },
};

export const MOCK_TOP_CHASES = [
  {
    id: 'tc-4-1',
    playerName: 'Anthony Volpe',
    variationName: 'Logofractor Rose Gold',
    category: 'Numbered Rookie Refractor',
    currentValue: 11998,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-1-2',
    playerName: 'Adley Rutschman',
    variationName: 'Sub Zero FrozenFractor',
    category: 'Numbered Rookie Refractor',
    currentValue: 8800,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-2-3',
    playerName: 'Gunnar Henderson',
    variationName: 'Superfractor',
    category: 'Superfractor',
    currentValue: 5750,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-79-4',
    playerName: 'Michael Harris II',
    variationName: 'Superfractor',
    category: 'Superfractor',
    currentValue: 5200,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-174-5',
    playerName: 'Triston Casas',
    variationName: 'Superfractor',
    category: 'Superfractor',
    currentValue: 3600,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-79-6',
    playerName: 'Michael Harris II',
    variationName: 'Logofractor Rose Gold',
    category: 'Numbered Rookie Refractor',
    currentValue: 3100,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-93-7',
    playerName: 'Josh Jung',
    variationName: 'Superfractor',
    category: 'Superfractor',
    currentValue: 2500,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-17-8',
    playerName: 'Shohei Ohtani',
    variationName: 'Superfractor',
    category: 'Superfractor',
    currentValue: 1725,
    rookieCard: false,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-93-9',
    playerName: 'Josh Jung',
    variationName: 'Logofractor Rose Gold',
    category: 'Numbered Rookie Refractor',
    currentValue: 1725,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-209-10',
    playerName: 'Jordan Walker',
    variationName: 'Red Wave',
    category: 'Numbered Rookie Refractor',
    currentValue: 1701,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-17-11',
    playerName: 'Shohei Ohtani',
    variationName: 'SP Variation Red Speckle',
    category: 'Short Print',
    currentValue: 1700,
    rookieCard: false,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-2-12',
    playerName: 'Gunnar Henderson',
    variationName: 'Logofractor Red',
    category: 'Numbered Rookie Refractor',
    currentValue: 1700,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-95-13',
    playerName: 'Corbin Carroll',
    variationName: 'Superfractor',
    category: 'Superfractor',
    currentValue: 1495,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-110-14',
    playerName: 'Garrett Mitchell',
    variationName: 'Superfractor',
    category: 'Superfractor',
    currentValue: 1450,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-93-15',
    playerName: 'Josh Jung',
    variationName: 'SP Variation Red Speckle',
    category: 'Short Print',
    currentValue: 1300,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-39-16',
    playerName: 'Ronald Acuna Jr.',
    variationName: 'Sub Zero FrozenFractor',
    category: 'Numbered Refractor',
    currentValue: 1300,
    rookieCard: false,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-17-17',
    playerName: 'Shohei Ohtani',
    variationName: 'Red',
    category: 'Numbered Refractor',
    currentValue: 1236.61,
    rookieCard: false,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-4-18',
    playerName: 'Anthony Volpe',
    variationName: 'Red Wave',
    category: 'Numbered Rookie Refractor',
    currentValue: 1236.11,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-79-19',
    playerName: 'Michael Harris II',
    variationName: 'SP Variation Red Speckle',
    category: 'Short Print',
    currentValue: 1225,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-200-20',
    playerName: 'Julio Rodriguez',
    variationName: 'Superfractor',
    category: 'Superfractor',
    currentValue: 1200,
    rookieCard: false,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-62-21',
    playerName: 'Aaron Judge',
    variationName: 'SP Variation Red Speckle',
    category: 'Short Print',
    currentValue: 1199,
    rookieCard: false,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-150-22',
    playerName: 'Mookie Betts',
    variationName: 'Superfractor',
    category: 'Superfractor',
    currentValue: 1194.99,
    rookieCard: false,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-2-23',
    playerName: 'Gunnar Henderson',
    variationName: 'Sub Zero FrozenFractor',
    category: 'Numbered Rookie Refractor',
    currentValue: 1107.01,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-209-24',
    playerName: 'Jordan Walker',
    variationName: 'Superfractor',
    category: 'Superfractor',
    currentValue: 1077.24,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
  {
    id: 'tc-69-25',
    playerName: 'Oswaldo Cabrera',
    variationName: 'Superfractor',
    category: 'Superfractor',
    currentValue: 1075,
    rookieCard: true,
    isAutograph: false,
    printRun: null,
  },
];

export const MOCK_PULL_RATES = [
  {
    id: 'pr-refractor',
    category: 'Refractor',
    oddsNumerator: 1,
    oddsDenominator: 3,
    probability: 0.33,
    source: 'Baseballcardpedia',
  },
  {
    id: 'pr-numbered-refractor',
    category: 'Numbered Refractor',
    oddsNumerator: 1,
    oddsDenominator: 96,
    probability: 0.01,
    source: 'Baseballcardpedia',
  },
  {
    id: 'pr-numbered-rookie-refractor',
    category: 'Numbered Rookie Refractor',
    oddsNumerator: 1,
    oddsDenominator: 96,
    probability: 0.01,
    source: 'Baseballcardpedia',
  },
  {
    id: 'pr-superfractor',
    category: 'Superfractor',
    oddsNumerator: 1,
    oddsDenominator: 37469,
    probability: 0.00,
    source: 'Baseballcardpedia',
  },
  {
    id: 'pr-insert',
    category: 'Insert',
    oddsNumerator: 1,
    oddsDenominator: 6,
    probability: 0.17,
    source: 'Baseballcardpedia',
  },
  {
    id: 'pr-short-print',
    category: 'Short Print',
    oddsNumerator: 1,
    oddsDenominator: 497,
    probability: 0.00,
    source: 'Baseballcardpedia',
  },
  {
    id: 'pr-base-auto',
    category: 'Base Auto',
    oddsNumerator: 1,
    oddsDenominator: 52,
    probability: 0.02,
    source: 'Baseballcardpedia',
  },
  {
    id: 'pr-refractor-auto',
    category: 'Refractor Auto',
    oddsNumerator: 1,
    oddsDenominator: 172,
    probability: 0.01,
    source: 'Baseballcardpedia',
  },
  {
    id: 'pr-numbered-autograph',
    category: 'Numbered Autograph',
    oddsNumerator: 1,
    oddsDenominator: 291,
    probability: 0.00,
    source: 'Baseballcardpedia',
  },
  {
    id: 'pr-memorabilia-relic',
    category: 'Memorabilia / Relic',
    oddsNumerator: 1,
    oddsDenominator: 575,
    probability: 0.00,
    source: 'Baseballcardpedia',
  },
];

// Grail cards — print run ≤ 10. These are the rarest cards in the set.
// Excluded from EV and ROI calculations (see CONTEXT.md for the /10 cutoff rationale).
// circulationStatus maps to the circulation_status column on the cards table in the
// real schema. The default value at data entry is 'unknown'.
export const MOCK_GRAIL_CARDS = [
  {
    id: 'gr2023-001',
    playerName: 'Shohei Ohtani',
    variationName: 'Black 1/1 Auto',
    printRun: 1,
    isAutograph: true,
    currentValue: 15000,
    circulationStatus: 'unknown',
  },
  {
    id: 'gr2023-002',
    playerName: 'Gunnar Henderson',
    variationName: 'Red /2 Refractor Auto',
    printRun: 2,
    isAutograph: true,
    currentValue: 4200,
    circulationStatus: 'in_circulation',
  },
  {
    id: 'gr2023-003',
    playerName: 'Corbin Carroll',
    variationName: 'Orange Refractor /5',
    printRun: 5,
    isAutograph: false,
    currentValue: 1200,
    circulationStatus: 'pulled_sold',
  },
  {
    id: 'gr2023-004',
    playerName: 'Jackson Holliday',
    variationName: 'Purple Refractor Auto /5',
    printRun: 5,
    isAutograph: true,
    currentValue: 2800,
    circulationStatus: 'unknown',
  },
  {
    id: 'gr2023-005',
    playerName: 'Julio Rodríguez',
    variationName: 'Gold Refractor Auto /10',
    printRun: 10,
    isAutograph: true,
    currentValue: 950,
    circulationStatus: 'in_circulation',
  },
  {
    id: 'gr2023-006',
    playerName: 'Elly De La Cruz',
    variationName: 'Red Refractor /10',
    printRun: 10,
    isAutograph: false,
    currentValue: 620,
    circulationStatus: 'unknown',
  },
  {
    id: 'gr2023-007',
    playerName: 'Adley Rutschman',
    variationName: 'Sapphire Auto /10',
    printRun: 10,
    isAutograph: true,
    currentValue: 580,
    circulationStatus: 'pulled_sold',
  },
];

// 12 months of sealed box market prices (used in the price trend chart)
export const MOCK_PRICE_HISTORY = [
  { date: 'May 24', price: 215 },
  { date: 'Jun 24', price: 228 },
  { date: 'Jul 24', price: 220 },
  { date: 'Aug 24', price: 210 },
  { date: 'Sep 24', price: 198 },
  { date: 'Oct 24', price: 195 },
  { date: 'Nov 24', price: 185 },
  { date: 'Dec 24', price: 200 },
  { date: 'Jan 25', price: 192 },
  { date: 'Feb 25', price: 188 },
  { date: 'Mar 25', price: 185 },
  { date: 'Apr 25', price: 190 },
];

// The five tiers from the project brief, each with a card count and
// the individual cards that appear in the checklist.
// All tiers have more than 5 cards so the expand/collapse button renders on each.
// Each card has a `number` field (card number from the set) so card-number search works.
// In the real schema these fields are `player_name` and `card_number`.
export const MOCK_CHECKLIST_TIERS = [
  {
    id: 'tier-1',
    label: 'Tier 1 — Base & Rookies',
    cardCount: 220,
    avgValue: 3.5,
    cards: [
      { id: 'c1-001', name: 'Shohei Ohtani',       number: '#1',       category: 'Base',         value: 18 },
      { id: 'c1-002', name: 'Mike Trout',           number: '#27',      category: 'Base',         value: 12 },
      { id: 'c1-003', name: 'Gunnar Henderson',     number: '#RC-GH',   category: 'Base Rookie',  value: 8  },
      { id: 'c1-004', name: 'Corbin Carroll',       number: '#RC-CC',   category: 'Base Rookie',  value: 6  },
      { id: 'c1-005', name: 'Jackson Holliday',     number: '#RC-JH',   category: 'Base Rookie',  value: 5  },
      { id: 'c1-006', name: 'Julio Rodríguez',      number: '#RC-JR',   category: 'Base',         value: 9  },
      { id: 'c1-007', name: 'Elly De La Cruz',      number: '#RC-EDL',  category: 'Base Rookie',  value: 7  },
      { id: 'c1-008', name: 'Adley Rutschman',      number: '#RC-AR',   category: 'Base',         value: 4  },
    ],
  },
  {
    id: 'tier-2',
    label: 'Tier 2 — Inserts & Short Prints',
    cardCount: 45,
    avgValue: 8.2,
    cards: [
      { id: 'c2-001', name: 'Julio Rodríguez',      number: '#FG-JR',   category: 'Insert',       value: 22 },
      { id: 'c2-002', name: 'Shohei Ohtani',        number: '#SP-1',    category: 'Short Print',  value: 45 },
      { id: 'c2-003', name: 'Elly De La Cruz',      number: '#FG-EDL',  category: 'Insert',       value: 15 },
      { id: 'c2-004', name: 'Gunnar Henderson',     number: '#SP-3',    category: 'Short Print',  value: 28 },
      { id: 'c2-005', name: 'Corbin Carroll',       number: '#FG-CC',   category: 'Insert',       value: 12 },
      { id: 'c2-006', name: 'Jackson Holliday',     number: '#FG-JH',   category: 'Insert',       value: 10 },
      { id: 'c2-007', name: 'Mike Trout',           number: '#SP-7',    category: 'Short Print',  value: 32 },
    ],
  },
  {
    id: 'tier-3',
    label: 'Tier 3 — Refractors',
    cardCount: 80,
    avgValue: 35,
    cards: [
      { id: 'c3-001', name: 'Gunnar Henderson',     number: '#RF-GH',   category: 'Rookie Refractor',  value: 95  },
      { id: 'c3-002', name: 'Jackson Holliday',     number: '#RF-JH',   category: 'Rookie Refractor',  value: 75  },
      { id: 'c3-003', name: 'Shohei Ohtani',        number: '#RF-1',    category: 'Refractor',         value: 55  },
      { id: 'c3-004', name: 'Corbin Carroll',       number: '#RF-CC',   category: 'Rookie Refractor',  value: 48  },
      { id: 'c3-005', name: 'Julio Rodríguez',      number: '#RF-JR',   category: 'Refractor',         value: 38  },
      { id: 'c3-006', name: 'Elly De La Cruz',      number: '#RF-EDL',  category: 'Rookie Refractor',  value: 42  },
    ],
  },
  {
    id: 'tier-4',
    label: 'Tier 4 — Autographs',
    cardCount: 40,
    avgValue: 120,
    cards: [
      { id: 'c4-001', name: 'Jackson Holliday',     number: '#CA-JH',   category: 'Base Auto',          value: 320 },
      { id: 'c4-002', name: 'Corbin Carroll',       number: '#CA-CC',   category: 'Refractor Auto',     value: 280 },
      { id: 'c4-003', name: 'Julio Rodríguez',      number: '#CA-JR',   category: 'Numbered Autograph', value: 450 },
      { id: 'c4-004', name: 'Gunnar Henderson',     number: '#CA-GH',   category: 'Refractor Auto',     value: 195 },
      { id: 'c4-005', name: 'Elly De La Cruz',      number: '#CA-EDL',  category: 'Base Auto',          value: 160 },
      { id: 'c4-006', name: 'Adley Rutschman',      number: '#CA-AR',   category: 'Base Auto',          value: 85  },
    ],
  },
  {
    // TODO: Replace with real Tier 5 cards from cards table — Patch Autos, Numbered Patch Autos, Memorabilia/Relic, Superfractor
    id: 'tier-5',
    label: 'Tier 5 — Premium Hits',
    cardCount: 15,
    avgValue: 450,
    cards: [
      { id: 'c5-001', name: 'Gunnar Henderson',     number: '#SF-1',    category: 'Superfractor',              value: 4500 },
      { id: 'c5-002', name: 'Julio Rodríguez',      number: '#PA-JR',   category: 'Patch Auto /10',            value: 1800 },
      { id: 'c5-003', name: 'Corbin Carroll',       number: '#PA-CC',   category: 'Patch Auto /25',            value: 950  },
      { id: 'c5-004', name: 'Jackson Holliday',     number: '#GR-JH',   category: 'Gold Refractor /50',        value: 620  },
      { id: 'c5-005', name: 'Mike Trout',           number: '#PA-MT',   category: 'Patch Auto /10',            value: 2200 },
      { id: 'c5-006', name: 'Shohei Ohtani',        number: '#PA-SO',   category: 'Patch Auto /50',            value: 750  },
      { id: 'c5-007', name: 'Elly De La Cruz',      number: '#NPA-EDL', category: 'Numbered Patch Auto /25',   value: 1100 },
      { id: 'c5-008', name: 'Adley Rutschman',      number: '#MR-AR',   category: 'Memorabilia Relic',         value: 280  },
    ],
  },
];
